name: dart_funcoes_colecoes
description: Modulo da academia do flutter de funcoes e colecoes
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
