name: dart_fundamentos
description: projeto referente ao curso de dart fundamentos da academia do flutter
version: 1.0.0
repository: https://github.com/jvddavid/academia-do-flutter.git

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
